blank_issues_enabled: true
contact_links:
  - name: Mailchimp Support
    url: https://mailchimp.com/help/mailchimp-support-options/
    about: Mailchimp Support can help with API issues related to your account
