name: Transactional SDK Issue Report
description: File an issue with one of the Transactional SDKs
labels: [transactional]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using the Mailchimp Transactional API!
        
        If your issue is with the behavior of the API, and not the SDK itself, we recommend reaching out to Mailchimp Support. Email support is available Monday through Friday between 9am and 5pm EST. When you’re logged in, click on the Support link at the bottom of any page to submit your request.
        
        We recommend using this issue form for:
        - Reporting bugs in the SDKs
        - Proposing changes to the Swagger spec
        
        By submitting you agree to the [Code of Conduct](https://github.com/mailchimp/mailchimp-client-lib-codegen/blob/main/code-of-conduct.md).

  - type: textarea
    id: what-issue
    attributes:
      label: What issue did you have?
      description: Also tell us, what did you expect to happen?
      placeholder:
      value:
    validations:
      required: true
  - type: dropdown
    id: language
    attributes:
      label: Language
      description: Which client are you using?
      options:
        - PHP
        - Node
        - Python
        - Ruby
    validations:
      required: false
