name: 🌐 Build Developer Site

on:
  push:
    paths:
      - 'spec/marketing.json'
      - 'spec/transactional.json'
    branches:
      - main

env:
  REBUILD_PROD: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # true iff push to main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: POST Prod Build Hook
        run: curl -X POST -d {} ${{ env.NETLIFY_PROD_BUILD_HOOK }}
        if: env.REBUILD_PROD == 'true'
        env:
          NETLIFY_PROD_BUILD_HOOK: ${{ secrets.NETLIFY_PROD_BUILD_HOOK }}
